LeaveRequest.ASP/LeaveRequest.ASP/Controllers/EmployeeLeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LeaveRequest.ASP.Common.Interface;
using LeaveRequest.ASP.DataAccess.Param;

namespace LeaveRequest.ASP.Controllers
{
    public class EmployeeLeaveController : Controller
    {
        private readonly IEmployeeLeaveService _employeeLeaveService;
        public EmployeeLeaveController() { }
        public EmployeeLeaveController(IEmployeeLeaveService employeeLeaveService)
        {
            this._employeeLeaveService = employeeLeaveService;
        }
        // GET: EmployeeLeave
        public ActionResult Index()
        {
            if (Session["Id"] != null)
            {
                var d = _employeeLeaveService.GetHiList();
                IEnumerable<EmployeeLeaveParam2> list_employeeleave = d.Select(c => new EmployeeLeaveParam2
                {
                    Id = c.Id,
                    Name = c.Employees.Name,
                    LeaveDays = c.LeaveDays,
                    Note = c.Note,
                    CreateDate = c.CreateDate,
                    ApprovalStatus = c.ApprovalStatus
                });
                return View(list_employeeleave);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }
        public ActionResult Create(int? id)
        {
            id = Convert.ToInt16(Session["Id"]);
            var employee = _employeeLeaveService.Get(id);
            var employeeleaveparam = new EmployeeLeaveParam(employee);

            IEnumerable<SelectListItem> _leavetype = _employeeLeaveService.LeaveType().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name

            });
            ViewBag.leavetype = _leavetype;
            return View(employeeleaveparam);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeLeaveParam employeeleaveparam)
        {
            if (ModelState.IsValid)
            {
                _employeeLeaveService.Insert(employeeleaveparam);
                return RedirectToAction("Index");
            }

            return View(employeeleaveparam);
        }
        [HttpPost]
        public ActionResult GetTypeLeave(int? id)
        {
                var obj = _employeeLeaveService.GetTypeLeave(id);
                return Content(obj.TotalDays.ToString());
        }

        [HttpPost]
        public ActionResult Edit(EmployeeLeaveParam2 employeeLeaveParam2)
        {
            if (ModelState.IsValid)
            {
                _employeeLeaveService.Update(employeeLeaveParam2);
                return RedirectToAction("Index");
            }
            return View(employeeLeaveParam2);
        }
    }
}

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/Admin.cshtml
@model LeaveRequest.ASP.BussinessLogic.Service.AdminService

@{
    ViewBag.Title = "Admin";
}

<h2>Index</h2>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            Leave Request
            @*@Html.ActionLink("Leave Request", "Index", "EmployeeLeave", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Employee", "IndexEmployee", "Admin")</li>
                <li>@Html.ActionLink("Department", "IndexDepartment", "Admin")</li>
                <li>@Html.ActionLink("Company", "IndexCompany", "Admin")</li>
                <li>@Html.ActionLink("LeaveType", "IndexLeaveType", "Admin")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-8">
        <hr />
        <table class="table">
            <tr>
                <th>
                    @*@Html.ActionLink("EMPLOYEE", "IndexEmployee")*@
                    <a href="~/Admin/IndexEmployee" class="btn btn-primary btn-lg">Employee &raquo;</a>
                </th>

                <th>
                    @*@Html.ActionLink("DEPARTMENT", "IndexDepartment")*@
                    <a href="~/Admin/IndexDepartment" class="btn btn-primary btn-lg">Department &raquo;</a>
                </th>

                <th>
                    @*@Html.ActionLink("COMPANY", "IndexCompany")*@
                    <a href="~/Admin/IndexCompany" class="btn btn-primary btn-lg">Company &raquo;</a>
                </th>

                <th>
                    @*@Html.ActionLink("LEAVE TYPE", "IndexLeave")*@
                    <a href="~/Admin/IndexLeave" class="btn btn-primary btn-lg">Leave Type &raquo;</a>
                </th>
        </table>
    </div>
</div>

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/CreateCompany.cshtml
@model LeaveRequest.ASP.DataAccess.Param.CompanyParam

@{
    ViewBag.Title = "CreateCompany";
}

<h2>CreateCompany</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/CreateDepartment.cshtml
@model LeaveRequest.ASP.DataAccess.Param.DepartmentParam

@{
    ViewBag.Title = "CreateDepartment";
}

<h2>CreateDepartment</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepartmentParam</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Companies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Companies, (IEnumerable<SelectListItem>)ViewBag.Preview, "Choose Company", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Companies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexDepartment")
</div>

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/CreateLeave.cshtml
@model LeaveRequest.ASP.DataAccess.Param.LeaveTypeParam

@{
    ViewBag.Title = "CreateLeave";
}

<h2>CreateLeave</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LeaveTypeParam</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexLeave")
</div>

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/DeleteCompany.cshtml
@model LeaveRequest.ASP.DataAccess.Param.CompanyParam

@{
    ViewBag.Title = "DeleteCompany";
}

<h2>DeleteCompany</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyParam</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexCompany")
        </div>
    }
</div>

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/EditCompany.cshtml
@model LeaveRequest.ASP.DataAccess.Param.CompanyParam

@{
    ViewBag.Title = "EditCompany";
}

<h2>EditCompany</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyParam</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexCompany")
</div>

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/IndexCompany.cshtml
@model IEnumerable<LeaveRequest.ASP.DataAccess.Param.CompanyParam>

@{
    ViewBag.Title = "IndexCompany";
}

<h2>Index</h2>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            Leave Request
            @*@Html.ActionLink("Leave Request", "Index", "EmployeeLeave", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Employee", "IndexEmployee", "Admin")</li>
                <li>@Html.ActionLink("Department", "IndexDepartment", "Admin")</li>
                <li>@Html.ActionLink("Company", "IndexCompany", "Admin")</li>
                <li>@Html.ActionLink("LeaveType", "IndexLeave", "Admin")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-8">
        <h4>Company Details</h4>
        @Html.ActionLink("Input Data", "CreateCompany")
        <hr />
        <table class="table">
            <tr>
                <th>
                    ID
                </th>

                <th>
                    Name
                </th>

                <th>
                    Action
                </th>

            </tr>
            @foreach (var company in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelCompany => company.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(modelCompany => company.Name)
                    </td>

                    <td>
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "EditCompany", new { id = company.Id }) |
                            @Html.ActionLink("Delete", "DeleteCompany", new { id = company.Id }) |
                            <a onclick="check(@company.Id)" class="btn btn-group">Delete</a>
                            @*<input type="submit" value="Cancel" class="btn btn-default" />*@
                            @*<a onclick="check(@company.Id)" class="btn btn-default">Cancel</a>*@
                            @*<a class="btn btn-danger" href="@Url.Action("Edit", new { id = employeeleave.Id })">Cancel</a>*@
                        </div>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>

@section scripts{

    <script src="~/Content/sweetalert/sweetalert.min.js"></script>
    <link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />

    <script>
        function check(id) {
            swal({
                title: "Are you sure?",
                text: "Really sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD7B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    url: "/Admin/DeleteCompany/",
                    data: {
                        'Id': id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: "Deleted",
                            text: "That data has been soft deleted!",
                        },
                            function () {
                                window.location.href = '/Admin/IndexCompany/';
                                //setTimeout(function () {
                                //    location.reload();
                                //}, 1200);
                            });
                    },
                    error: function (response) {
                        swal("Oops", "We couldn't connect to the server!", "Error");
                    }
                });

            });
        }
    </script>
}

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/IndexDepartment.cshtml
@model IEnumerable<LeaveRequest.ASP.DataAccess.Param.DepartmentParam>

@{
    ViewBag.Title = "IndexDepartment";
}

<h2>Index Department</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            Leave Request
            @*@Html.ActionLink("Leave Request", "Index", "EmployeeLeave", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Employee", "IndexEmployee", "Admin")</li>
                <li>@Html.ActionLink("Department", "IndexDepartment", "Admin")</li>
                <li>@Html.ActionLink("Company", "IndexCompany", "Admin")</li>
                <li>@Html.ActionLink("LeaveType", "IndexLeave", "Admin")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <h4>Department Details</h4>
        @Html.ActionLink("Input Data", "CreateDepartment")
        <hr />
        <table class="table">
            <tr>
                <th>
                    ID
                </th>

                <th>
                    Name
                </th>

                <th>
                    Company
                </th>

                <th>
                    Action
                </th>

            </tr>
            @foreach (var department in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelDepartment => department.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(modelDepartment => department.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelDepartment => department.Companies)
                    </td>

                    <td>
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "EditDepartment", new { id = department.Id }) |
                            @Html.ActionLink("Delete", "DeleteDepartment", new { id = department.Id }) |
                            <a onclick="check(@department.Id)" class="btn btn-group">Delete</a>
                            @*<input type="submit" value="Cancel" class="btn btn-default" />*@
                            @*<a onclick="check(@company.Id)" class="btn btn-default">Cancel</a>*@
                            @*<a class="btn btn-danger" href="@Url.Action("Edit", new { id = employeeleave.Id })">Cancel</a>*@
                        </div>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>

@section scripts{

    <script src="~/Content/sweetalert/sweetalert.min.js"></script>
    <link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />

    <script>
        function check(id) {
            swal({
                title: "Are you sure?",
                text: "Really sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD7B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    url: "/Admin/DeleteDepartment/",
                    data: {
                        'Id': id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: "Deleted",
                            text: "That data has been soft deleted!",
                        },
                            function () {
                                window.location.href = '/Admin/IndexDepartment/';
                                //setTimeout(function () {
                                //    location.reload();
                                //}, 1200);
                            });
                    },
                    error: function (response) {
                        swal("Oops", "We couldn't connect to the server!", "Error");
                    }
                });

            });
        }
    </script>
}

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/IndexEmployee.cshtml
@model IEnumerable<LeaveRequest.ASP.DataAccess.Param.EmployeeParam>

@{
    ViewBag.Title = "IndexEmployee";
}

<h2>Index Employee</h2>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            Leave Request
            @*@Html.ActionLink("Leave Request", "Index", "EmployeeLeave", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Employee", "IndexEmployee", "Admin")</li>
                <li>@Html.ActionLink("Department", "IndexDepartment", "Admin")</li>
                <li>@Html.ActionLink("Company", "IndexCompany", "Admin")</li>
                <li>@Html.ActionLink("LeaveType", "IndexLeave", "Admin")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <h4>Employee Details</h4>
        @Html.ActionLink("Input Data", "CreateEmployee")
        <hr />
        <table class="table">
            <tr>
                <th>
                    ID
                </th>

                <th>
                    Name
                </th>

                <th>
                    Email
                </th>

                <th>
                    Phone
                </th>

                <th>
                    Join Date
                </th>

                <th>
                    Job Title
                </th>

                <th>
                    Status
                </th>

                <th>
                    Total Childs
                </th>

                <th>
                    This Year
                </th>

                <th>
                    Last Year
                </th>

                <th>
                    Department
                </th>

                <th>
                    Manager
                </th>

                <th>
                    Action
                </th>

            </tr>
            @foreach (var employee in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelEmployee => employee.Id)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.Email)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.Phone)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.JoinDate)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.JobTitle)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.Status)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.TotalChilds)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.ThisYear)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.LastYear)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.Departments)
                </td>

                <td>
                    @Html.DisplayFor(modelEmployee => employee.ManagerId)
                </td>

                <td>
                    <div class="btn-group">
                        @Html.ActionLink("Edit", "EditDepartment", new { id = employee.Id }) |
                        @Html.ActionLink("Delete", "DeleteDepartment", new { id = employee.Id }) |
                        <a onclick="check(@employee.Id)" class="btn btn-group">Delete</a>
                        @*<input type="submit" value="Cancel" class="btn btn-default" />*@
                        @*<a onclick="check(@company.Id)" class="btn btn-default">Cancel</a>*@
                        @*<a class="btn btn-danger" href="@Url.Action("Edit", new { id = employeeleave.Id })">Cancel</a>*@
                    </div>
                </td>

            </tr>
            }
        </table>
    </div>
</div>

@section scripts{

    <script src="~/Content/sweetalert/sweetalert.min.js"></script>
    <link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />

    <script>
        function check(id) {
            swal({
                title: "Are you sure?",
                text: "Really sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD7B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    url: "/Admin/DeleteEmployee/",
                    data: {
                        'Id': id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: "Deleted",
                            text: "That data has been soft deleted!",
                        },
                            function () {
                                window.location.href = '/Admin/IndexEmployee/';
                                //setTimeout(function () {
                                //    location.reload();
                                //}, 1200);
                            });
                    },
                    error: function (response) {
                        swal("Oops", "We couldn't connect to the server!", "Error");
                    }
                });

            });
        }
    </script>
}

LeaveRequest.ASP/LeaveRequest.ASP/Views/Admin/IndexLeave.cshtml
@model IEnumerable<LeaveRequest.ASP.DataAccess.Param.LeaveTypeParam>

@{
    ViewBag.Title = "IndexLeave";
}

<h2>Index</h2>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            Leave Request
            @*@Html.ActionLink("Leave Request", "Index", "EmployeeLeave", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Employee", "IndexEmployee", "Admin")</li>
                <li>@Html.ActionLink("Department", "IndexDepartment", "Admin")</li>
                <li>@Html.ActionLink("Company", "IndexCompany", "Admin")</li>
                <li>@Html.ActionLink("LeaveType", "IndexLeave", "Admin")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-8">
        <h4>Leave Type Details</h4>
        @Html.ActionLink("Input Data", "CreateLeave")
        <hr />
        <table class="table">
            <tr>
                <th>
                    ID
                </th>

                <th>
                    Name
                </th>

                <th>
                    Total Days
                </th>

                <th>
                    Action
                </th>

            </tr>
            @foreach (var leavetype in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelLeaveType => leavetype.Id)
                    </td>

                    <td>
                        @Html.DisplayFor(modelLeaveType => leavetype.Name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelLeaveType => leavetype.TotalDays)
                    </td>

                    <td>
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "EditLeave", new { id = leavetype.Id }) |
                            @Html.ActionLink("Delete", "DeleteLeave", new { id = leavetype.Id }) |
                            <a onclick="check(@leavetype.Id)" class="btn btn-group">Delete</a>
                            @*<input type="submit" value="Cancel" class="btn btn-default" />*@
                            @*<a onclick="check(@company.Id)" class="btn btn-default">Cancel</a>*@
                            @*<a class="btn btn-danger" href="@Url.Action("Edit", new { id = employeeleave.Id })">Cancel</a>*@
                        </div>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>

@section scripts{

    <script src="~/Content/sweetalert/sweetalert.min.js"></script>
    <link href="~/Content/sweetalert/sweetalert.css" rel="stylesheet" />

    <script>
        function check(id) {
            swal({
                title: "Are you sure?",
                text: "Really sure?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD7B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    url: "/Admin/DeleteLeave/",
                    data: {
                        'Id': id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: "Deleted",
                            text: "That data has been soft deleted!",
                        },
                            function () {
                                window.location.href = '/Admin/IndexLeave/';
                                //setTimeout(function () {
                                //    location.reload();
                                //}, 1200);
                            });
                    },
                    error: function (response) {
                        swal("Oops", "We couldn't connect to the server!", "Error");
                    }
                });

            });
        }
    </script>
}